"use client";

import { useEffect, useState } from "react";
import { useChefIA } from "@/lib/store";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input, Label } from "@/components/ui/input";
import { Package } from "lucide-react";
import { listInsumos, addInsumo } from "@/lib/supabase/queries";
import type { Insumo } from "@/types";

export default function EstoquePage() {
  const { profile } = useChefIA();
    const [insumos, setInsumos] = useState<Insumo[]>([]);
      const [carregando, setCarregando] = useState(true);
        const [aberto, setAberto] = useState(false);
          const [nome, setNome] = useState("");
            const [unidade, setUnidade] = useState("g");
              const [quantidadeEstoque, setQuantidadeEstoque] = useState("");
                const [quantidadeMinima, setQuantidadeMinima] = useState("");
                  const [custoUnitario, setCustoUnitario] = useState("");

                    useEffect(() => {
                        if (profile.plano !== "premium") return;
                            listInsumos()
                                  .then(setInsumos)
                                        .finally(() => setCarregando(false));
                                          }, [profile.plano]);

                                            async function salvar() {
                                                if (!nome.trim()) return;
                                                    await addInsumo({
                                                          nome,
                                                                unidade,
                                                                      quantidadeEstoque: Number(quantidadeEstoque) || 0,
                                                                            quantidadeMinima: Number(quantidadeMinima) || 0,
                                                                                  custoUnitario: Number(custoUnitario) || 0,
                                                                                      });
                                                                                          const atualizados = await listInsumos();
                                                                                              setInsumos(atualizados);
                                                                                                  setNome("");
                                                                                                      setUnidade("g");
                                                                                                          setQuantidadeEstoque("");
                                                                                                              setQuantidadeMinima("");
                                                                                                                  setCustoUnitario("");
                                                                                                                      setAberto(false);
                                                                                                                        }
                                                                                                                        
                                                                                                                          if (profile.plano !== "premium") {
                                                                                                                              return (
                                                                                                                                    <div className="animate-fade-up max-w-2xl">
                                                                                                                                            <header className="mb-8">
                                                                                                                                                      <h1 className="font-display text-3xl">Controle de estoque</h1>
                                                                                                                                                                <p className="mt-1 text-cacau/60 dark:text-cream/60">Recurso exclusivo do plano PRO.</p>
                                                                                                                                                                        </header>
                                                                                                                                                                                <Card className="py-10 text-center">
                                                                                                                                                                                          <p className="text-sm text-cacau/60 dark:text-cream/60">
                                                                                                                                                                                                      Faça upgrade para o plano PRO para liberar o controle de estoque.
                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                          <div className="animate-fade-up max-w-2xl">
                                                                                                                                                                                                                                                <header className="mb-8 flex items-center justify-between">
                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                  <h1 className="font-display text-3xl">Controle de estoque</h1>
                                                                                                                                                                                                                                                                            <p className="mt-1 text-cacau/60 dark:text-cream/60">
                                                                                                                                                                                                                                                                                        {insumos.length} insumo{insumos.length !== 1 ? "s" : ""} cadastrado{insumos.length !== 1 ? "s" : ""}
                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                  <Button onClick={() => setAberto(!aberto)}>{aberto ? "Cancelar" : "Novo insumo"}</Button>
                                                                                                                                                                                                                                                                                                                        </header>
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                              {aberto && (
                                                                                                                                                                                                                                                                                                                                      <Card className="mb-6">
                                                                                                                                                                                                                                                                                                                                                <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                            <Label htmlFor="nome">Nome do insumo</Label>
                                                                                                                                                                                                                                                                                                                                                                        <Input id="nome" value={nome} onChange={(e) => setNome(e.target.value)} placeholder="Ex: Farinha de trigo" />
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                            <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                        <Label htmlFor="unidade">Unidade</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                    <Input id="unidade" value={unidade} onChange={(e) => setUnidade(e.target.value)} placeholder="g, ml, un" />
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Label htmlFor="quantidadeEstoque">Quantidade em estoque</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Input id="quantidadeEstoque" type="number" value={quantidadeEstoque} onChange={(e) => setQuantidadeEstoque(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Label htmlFor="quantidadeMinima">Quantidade mínima (alerta)</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Input id="quantidadeMinima" type="number" value={quantidadeMinima} onChange={(e) => setQuantidadeMinima(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Label htmlFor="custoUnitario">Custo unitário (R$)</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Input id="custoUnitario" type="number" value={custoUnitario} onChange={(e) => setCustoUnitario(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button onClick={salvar}>Salvar insumo</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {carregando ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-cacau/60 dark:text-cream/60">Carregando...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : insumos.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Card className="flex flex-col items-center gap-3 py-12 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Package size={32} className="text-framboesa" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="font-display text-xl">Nenhum insumo cadastrado</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="max-w-sm text-sm text-cacau/60 dark:text-cream/60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Cadastre os ingredientes que você tem em casa para começar a controlar seu estoque.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {insumos.map((i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Card key={i.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="font-medium">{i.nome}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-1 text-sm text-cacau/60 dark:text-cream/60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {i.quantidadeEstoque} {i.unidade} em estoque
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {i.quantidadeEstoque <= i.quantidadeMinima && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-1 text-xs text-framboesa">Estoque baixo</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
